version: "3.9"

services:
  app-api:
    build:
      context: ./app-api
    ports:
      - 8000:8000
    env_file:
      - .env
    networks:
      - app_network
    volumes:
      - ./app-api:/app
    command: sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --workers 1"
    depends_on:
      - db

  db:
    image: postgres:14.1-alpine
    networks:
      - app_network
    env_file:
      - ./.env
    volumes:
      - db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5051:80
    networks:
      - app_network
    env_file:
      - ./.env
    depends_on:
      - db

networks:
  app_network:
    driver: bridge

volumes:
  db:
    driver: local