FROM python:3.11.5-slim

ENV PYTHONNUNBUFFERED 1
ENV PATH="/root/.local/bin:$PATH"
ENV PYTHONPATH='./'

WORKDIR /app

COPY ./app /
COPY ./.env /
COPY ./poetry.lock /
COPY ./pyproject.toml /
COPY ./logging.conf /
COPY ./alembic.ini /



RUN apt-get update -y && apt-get install curl -y \
    && curl -sSL https://install.python-poetry.org | python3 - \
    && poetry config virtualenvs.create false \
    && poetry install \
    && apt-get remove curl -y



